### ISSUE TITLE
chrome on MacOS

### ISSUE THREAD

**Issue by xunhuang** [jmcker/Peer-to-Peer-Cue-System#14]
hi, cool system. 
I tried to run the demo on Chrome (latest) in MacOS and was not successful (even though the same works on Safari and Firefox). 
The problem was that the sender issues a peer connect command, server receives the command (and thought it is connected). but the sender never saw that the connection was established and get stuck there.

![image](https://user-images.githubusercontent.com/729879/93137245-02272780-f692-11ea-95e4-b031e8ac1bd4.png)

**Comment by xunhuang** [comment]
found the issue. it's my own issue. It turns out one of my chrome extensions interfered. after its removal, everything works.

**Comment by jmcker** [comment]
What extension was this? I've been seeing a similar situation in Chrome on Windows. Opening everything in Incognito or even just one half of the connection in Incognito works, but the same "stall" that you saw occurs if both are open in normal Chrome. 

I had yet to diagnose if it's being caused by an extension or something with mDNS.

**Comment by xunhuang** [comment]
I removed a whole bunch of them, only left LastPass after clean up.
Here are the ones I remember:
- All google plugin - Google Drive, Google Sheets, etc...
- PureVPN
- A plugin that I wrote myself.
- ...
I wasn't sure the problem was due to the extensions at first, so I wasn't
keeping track. I should have tracked it.

If you want to diagnose, you can just start chrome in Incognito mode, and
that makes it no extension for sure. If even that doesn't work, I would go
down other paths.
